### ISSUE TITLE
Approval date is incorrect in ClinVar submitter service

### ISSUE THREAD

**Issue by marinadistefano** [clingen-data-model/clinvar-submitter#35]
The ClinVar submission generator is taking the date that I saved it as approved (e.g. today’s date) instead of the actual approval date. When I went to check on this in the eRepo, it’s the same problem.

Here’s an example: https://curation.clinicalgenome.org/variant-central/fa2cb91c-ba30-4b0c-a7b5-2d3cd884ef28/interpretation/88d051fa-2e2f-4648-8461-90b03b59dca0

And the eRepo link:
https://erepo.clinicalgenome.org/evrepo/ui/interpretation/88d051fa-2e2f-4648-8461-90b03b59dca0

**Comment by larrybabb** [comment]
we need to make the VCI team aware of this by getting it cross linked on their ticket board. while the code is shared, the VCI team has the final responsibility for deploying it.

I linked this issue to the VCI's git issue list [here](https://github.com/ClinGen/gene-and-variant-curation-tools/issues/208).

**Comment by larrybabb** [comment]
Waiting on analysis from Stanford VCI team.

**Comment by larrybabb** [comment]
@marinadistefano you may want to remind the VCI team that we are waiting on them to get this resolved and that I am willing to help with the effort. I think this is a pretty small project, but it will involve coordination across Stanford (VCI), Baylor (eRepo) and us (Clinvar Submitter & DataExchange).

**Comment by larrybabb** [comment]
@marinadistefano the VCI team has corrected this issue. We would like you to re-approve and re-publish the example submission that you referenced at the start of this issue and verify that the correct approval date is getting generated for the clinvar submission as well as ending up being published to the erepo.

The most immediate fix for any other past approval date errors will require the same action. Since these will all require resubmission to CliNVar to get them to have the proper date there isn't a much easier solution.

Please let me know how the verification goes and if there are questions or concerns on handling the other errant historical entries.

**Comment by larrybabb** [comment]
@marinadistefano validated that all is working as described.
